"""Where the dashboard finds its data, set through environment variables.

The `hexoreview run` command sets these for you; set them by hand only if you
launch `panel serve` yourself.
"""

from __future__ import annotations

import os
from pathlib import Path


def _path(env: str, default: str) -> Path:
    return Path(os.environ.get(env, default)).expanduser()


class Config:
    def __init__(self):
        self.blinded_dir = _path("HEXOREVIEW_BLINDED_DIR", "./blinded")
        self.db_path = _path("HEXOREVIEW_DB", "./review/reviews.sqlite")
        self.cache_dir = _path("HEXOREVIEW_CACHE", "./review/cache")
        self.export_dir = _path("HEXOREVIEW_EXPORT", "./export")
        # coordinator-only: joining marks back to patients needs the private map
        self.map_path = _path("HEXOREVIEW_MAP", "./private/blinding_map.csv")
        # anonymized training clips + their manifest, shown to reviewers in the
        # "Training samples" menu; generated by
        #   hexoreview scan <source> --samples-csv seizures.csv
        self.samples_dir = _path("HEXOREVIEW_SAMPLES", "./review/samples")
        # elapsed time from the start of the recording is the default; time of
        # day can be turned on, but it hints at which night is on screen
        self.clock_mode = os.environ.get("HEXOREVIEW_CLOCK", "0") == "1"

    def __repr__(self):
        return (
            f"Config(blinded_dir={self.blinded_dir}, db={self.db_path}, "
            f"cache={self.cache_dir}, map={self.map_path}, "
            f"samples={self.samples_dir})"
        )


config = Config()